### PR TITLE
.github: Run tests in fedora 37 as well

### PR DESCRIPTION
**Pull request by jjardon**
And remove soon to be deprecated fedora 35

Currently failing because python 3.11 is not supported: #1802

### CODE REVIEW

**Comment by ghost** [comment]
Looks to be failing due to missing `longintrepr.h` needed by pyroaring:

      pyroaring/pyroaring.cpp:220:12: fatal error: longintrepr.h: No such file or directory

This appears to be a bug in Cython which was already fixed last year: https://github.com/cython/cython/issues/4461

Suggested fix would be to update the minimum Cython version 0.29.25

**Comment by juergbi** [comment]
> Suggested fix would be to update the minimum Cython version 0.29.25

This has been merged in the meantime as part of #1778.

**Comment by jjardon** [comment]
Seems we still have he same problem: https://github.com/apache/buildstream/actions/runs/3698106262/jobs/6263904645
```
      pyroaring/pyroaring.cpp:220:12: fatal error: longintrepr.h: No such file or directory
        220 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
```

**Comment by cs-shadow** [comment]
pyroraing should be fine after https://github.com/apache/buildstream/pull/1806 - we just had pinned an older release, newer versions are fine.

the next issue is with grpcio - see https://github.com/apache/buildstream/pull/1807 for how that fails. https://github.com/grpc/grpc/pull/31960 should backport 3.11 support to the minor version we're on. However this  also means that BuildStream (or at least its testsuite) doesn't work with grpicio versions 1.49 and above, which might be a problem in its own right.
