### PR TITLE
bst-1: Use collections.abc instead collections

### LINKED ISSUE #1483: Failed to build with Python 3.10
buildstream fails to build with Python 3.10.0a5.

```python
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
make: *** [Makefile:107: sessions] Error 1
```

- OS: Fedora 35
- Buildstream: 1.6.1

[Full build log](https://kojipkgs.fedoraproject.org//work/tasks/966/69520966/build.log).

https://docs.python.org/3.10/whatsnew/changelog.html

### PR DESCRIPTION
**Pull request by jjardon**
Collections Abstract Base Classes has been moved to the collections.abc module. They were deprecated since version 3.3, will be removed from the old location in version 3.10

See https://docs.python.org/3/library/collections.html#module-collections

Fixes #1483

### CODE REVIEW

**Comment by gtristan** [comment]
Thanks !
