### ISSUE TITLE
Failed to build with Python 3.10

### ISSUE THREAD

**Issue by tim77** [apache/buildstream#1483]
buildstream fails to build with Python 3.10.0a5.

```python
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/builddir/build/BUILD/buildstream-1.6.1/doc/bst2html.py", line 38, in <module>
    from buildstream import _yaml
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/__init__.py", line 33, in <module>
    from .source import Source, SourceError, Consistency, SourceFetcher
  File "/builddir/build/BUILD/buildstream-1.6.1/buildstream/source.py", line 150, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
make: *** [Makefile:107: sessions] Error 1
```

- OS: Fedora 35
- Buildstream: 1.6.1

[Full build log](https://kojipkgs.fedoraproject.org//work/tasks/966/69520966/build.log).

https://docs.python.org/3.10/whatsnew/changelog.html

**Comment by tim77** [comment]
Fixed in `1.6.2`. TY!
